### ISSUE TITLE
Preserve meta

### ISSUE THREAD

**Issue by darkleaf** [leonoel/cloroutine#11]
```clojure
(let [example ^:foo [1]]
  (meta example)) ;; #=> {:foo true}

(let [example (cr {}
                  ^:foo [1])]
  (meta (example))) ;; #=> {:file "/Users/mihail/projects/github/effect/src/darkleaf/effect/core.cljc", :tag clojure.lang.PersistentVector}
```

I expect that values preserve they literal metadata.

**Comment by darkleaf** [comment]
I've dug this issue a little bit.
I thing it should convert `^:foo [1]` into `(with-meta [1] {:foo true}` inside `ssa / add-breaking / :with-meta`. 
May be you suggest a better solution?

**Comment by leonoel** [comment]
You're right, that's where the metadata is lost. The map is stored in the `:meta` field of the [with-meta node](https://clojure.github.io/tools.analyzer.jvm/spec/quickref.html#with-meta), which is not currently used. Wrapping the form in a `(with-meta)` looks like a valid strategy to me, the hardest part should be to handle all cases properly (especially, check consistency wrt the clojurescript analyzer).

**Comment by darkleaf** [comment]
https://github.com/clojure/core.async/blob/master/src/main/clojure/clojure/core/async/impl/ioc_macros.clj#L798-L804

**Comment by darkleaf** [comment]
Can you explain difference between `ssa / add-closing` and `ssa / add-breaking`?

**Comment by leonoel** [comment]
Sure. In breaking mode, we walk the ast and convert it to ssa. In closing mode, we walk the ast and rewrite it as-is. We start the walk in breaking mode, and when we encounter a closure (fn, letfn, reify) we switch to closing mode.

Compared to `core.async`, we need a closing walk instead of just pasting out the form as-is because it allows us to keep track of captured bindings, and this information is needed in the next pass to optimize slot allocation.

**Comment by darkleaf** [comment]
Unfortunately clojurescript version of core.async doesn't support literal meta. Is it theoretically possible in cloroutine?

```clojure
;; cljs
(ns darkleaf.effect.example
  (:require
   [cljs.core.async :as a]))

(let [x (a/go ^:foo [:x])]
  (a/go
    (prn (meta (a/<! x))))) ;; nil
```

```clojure
(ns darkleaf.effect.example
  (:require
   [clojure.core.async :as a]))

(let [x (a/go ^:foo [:x])]
  (a/go
    (prn (meta (a/<! x))))) ;; {:foo true}
```

**Comment by darkleaf** [comment]
https://ask.clojure.org/index.php/8966/a-literal-meta-in-cljs-core-async

**Comment by leonoel** [comment]
`cljs.analyzer` seems to be in sync with `clojure.tools.analyzer.jvm` for the `with-meta` node, so it should be straightforward to implement this in a portable way.

Do you have something in progress on this one ? If not, I should be able to tackle it pretty soon.

**Comment by darkleaf** [comment]
It's not critical for me now. I found another solution. So, you take your time.

**Comment by leonoel** [comment]
Fixed in version 10

**Comment by darkleaf** [comment]
Thanks @leonoel.
It also works in cljs!
