### ISSUE TITLE
Requires ClojureScript dependency on classpath

### ISSUE THREAD

**Issue by lgrapenthin** [leonoel/cloroutine#21]
impl.cljc requires `cljs.analyzer` and `cljs.env` for cljs macros.

To avoid this problem, one approach would be:

- split up impl.cljc so that it provides an impl_clj and impl_cljs entrypoint namespace
- require the respective ns using a reader conditional from core.cljc

**Comment by leonoel** [comment]
Keep in mind we need to support :
* clojure compiler targeting clojure
* clojure compiler targeting clojurescript
* clojurescript compiler targeting clojurescript
File extensions and reader conditionals are about the compiler language, but what we want is to conditionally require based on the target language.

**Comment by lgrapenthin** [comment]
https://github.com/cgrand/macrovich can be used as a tool or reference (code is very little) to avoid potential problems, however the clj based cljs compiler only reads clj for macroexpansion, if required by previously read cljs.

**Comment by kawas44** [comment]
Hello,
I would also love to use Missionary and build a standalone uberjar without 20 Mb of Clojurescript/Google cruft.

I have tried _macrovich_ but was not able to make the code usable from clj and cljs at the same time :thinking: 

I have tried the _core.async_ solution, which is to create a separate namespace. Obviously a big disadvantage is the huge duplication of code. But at least, everything works correctly. You can see my commit on branch [`split-cljcljs-duplicate`](/kawas44/cloroutine/tree/split-cljcljs-duplicate).

I have tried to dynamically require Clojurescript dependencies when available to provide a dedicate analyze implementation function. No code duplication but it may be a bit slower (could we use caching?). You can see my commit on branch [`split-cljcljs-dynamic`](/kawas44/cloroutine/tree/split-cljcljs-dynamic).

I have tested my two branches with an external simple project and everything seems to work fine.

What do think about those solutions?

**Comment by kawas44** [comment]
Hello @leonoel,

Using the _cloroutine_ branch with dynamic loading and moving _missionary_ clojurescript dependency to the `cljs-test` alias I was able to run _missionary_ Clj tests and Cljs tests (clojurescript & planck) without errors.

The [dynamic loading solution](https://github.com/leonoel/cloroutine/compare/master...kawas44:cloroutine:split-cljcljs-dynamic) look promising. What do you think?

**Comment by leonoel** [comment]
Fixed in `12`
