### ISSUE TITLE
Warnings when loading missionary.core

### ISSUE THREAD

**Issue by slifin** [leonoel/cloroutine#23]
<img width="932" alt="Screenshot 2022-04-10 at 22 06 39" src="https://user-images.githubusercontent.com/198857/162639854-0966a09d-3672-487c-9600-72f6047f3322.png">

![deps](https://user-images.githubusercontent.com/198857/162639893-eb5e53a1-9c12-46b7-b927-5ea3a1bc006a.png)

Dependency graph on a fairly minimal app that uses Missionary + Clojure 1.11.1  ^

In recent versions of Clojure they've introduced a few new functions such as `update-vals` these were historically already defined in `clojure.tools.analyzer` 

If we look at Clojure tools analyzer today they've fixed those warnings for the new version of Clojure: https://github.com/clojure/tools.analyzer/blob/master/src/main/clojure/clojure/tools/analyzer/passes/uniquify.clj
(by explicitly excluding those functions which prevents the warning)

but the version of Clojure tools analyzer we're depending on in this project (indirectly via `org.clojure/tools.analyzer.jvm`) does not: 
https://github.com/clojure/tools.analyzer/blob/20a6aac20045c6d9bb82ccbb40f3c86ca839f4e3/src/main/clojure/clojure/tools/analyzer/passes/uniquify.clj

Is it possible to bump `org.clojure/tools.analyzer.jvm` dependency up?

**Comment by leonoel** [comment]
Fixed in release `11`
