### ISSUE TITLE
Tagged literals cause a freeze

### ISSUE THREAD

**Issue by simonacca** [leonoel/cloroutine#26]
I've been using [this implementation](https://gist.github.com/leonoel/79ac90440584ec518f2acf161996a479) of async/await, and have noticed that whenever I use the `#js` [tagged literal](https://clojure.org/reference/reader#tagged_literals), the coroutine times out.

This for example does the trick:
```cljs
(async #js {"key" "val"})
```

**Comment by leonoel** [comment]
Fixed in release `11`
